---
title: "Create_edgelist"
author: "Jakob Mørup"
date: "12/28/2021"
output: html_document
---
```{r}
library(pacman)

p_load(tidyverse, tidytext, jsonlite)
```


#test for actual data
```{r}

# 
# path <- "../EC_Reddit_CaseStudy-main/data/Categories_raw_data/guncontrol_01-06-2020_01-01-2021/guncontrol_01-06-2020_01-01-2021"
# path2 <- "../EC_Reddit_CaseStudy-main/data/Categories_raw_data/guncontrol_01-01-2016_01-01-2021/guncontrol_01-01-2016_01-01-2021"
# 
# files <- dir(path, pattern = "*.json")
# files2 <- dir(path2, pattern = "*.json")
# 
# 
# data <- files %>%
# 	map_df(~fromJSON(file.path(path, .), flatten = TRUE))
# 
# data <- data$comments
# 
# #data <- data %>%
# #	select(author, id, clean_text, subreddit)
# 
# 
# data$pol_leaning <- case_when(
# 	data$subreddit == "guncontrol" ~ "anti",
# 	data$subreddit == "liberalgunowners" ~ "pro",
# 	data$subreddit == "progun" ~ "pro"
# )
# 
# data2 <- files2 %>%
# 	map_df(~fromJSON(file.path(path2, .), flatten = TRUE))
# 
# data2 <- data2$comments
# 
# data2 <-  data2  %>%
# 	mutate(pol_leaning ="anti")
# 
# 
# data_comb <- rbind(data,data2)
# data_comb <- data_comb %>%
# 	select(-time_period) %>%
# 	distinct()
# 
# 
# data_comb <- data_comb %>%
# 	select(author, id, parent_id, clean_text, subreddit, pol_leaning)
# 
# 
# 
# data_comb <- read_csv("data_comb_guns.csv")
# 

```


```{r}
religion_comments <- read_csv("religionvsatheist2yrs_allcollumns.csv")
religion_comments <- religion_comments %>% 
	select(author, id, parent_id)
religion_comment_ids <- religion_comments %>% 
	select(author, id)


religion_posts <- read_csv("religion2yrs_posts.csv")
religion_posts <-  religion_posts %>% 
	select(author, id)


idlist <-  rbind(religion_comment_ids, religion_posts	)
```



#create the edgelist
```{r}

edgelist <-  data.frame()

for (i in 1:nrow(religion_comments)) {
	from = religion_comments$author[i]
	
	comment = religion_comments$id[i]
	
	comment_to = substr(religion_comments$parent_id[i], 4, 10)
	
	parent_id_row = idlist[which(idlist$id == comment_to),]
	
	to = if (nrow(parent_id_row)== 1) { parent_id_row$author } else{ "NA"}
	
	edge = c(from, to)
	
	edgelist <- rbind(edgelist,edge)
	}



colnames(edgelist) <- c("From", "to")

# 


edgelist2 <- edgelist %>% 
	filter(to != "NA") %>% 
	distinct()

write_csv(edgelist2, "religion_edgelist_2yrs.csv")


```

